### ISSUE TITLE
api:dev: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Rakoski** [Rakoski/leetcode-problem-storer#1]
While trying to start my own expressjs server, I am getting this error:

`api:dev: CJS dist/index.js 4.67 MB
api:dev: CJS ⚡️ Build success in 1200ms
api:dev: CLI Watching for changes in "."
api:dev: CLI Ignoring changes in "**/{.git,node_modules}/**" | "dist"
api:dev: /home/mateus/WebstormProjects/leetcode-problem-storer/my-turborepo/apps/api/dist/index.js:45435
api:dev:     var AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf(function() {
api:dev:                                         ^
api:dev: 
api:dev: TypeError: Cannot convert undefined or null to object
api:dev:     at Function.getPrototypeOf (<anonymous>)
api:dev:     at ../../node_modules/.pnpm/whatwg-url@11.0.0/node_modules/whatwg-url/lib/utils.js (/home/mateus/WebstormProjects/leetcode-problem-storer/my-turborepo/apps/api/dist/index.js:45435:41)
api:dev:     at __require (/home/mateus/WebstormProjects/leetcode-problem-storer/my-turborepo/apps/api/dist/index.js:46:50)
api:dev:     at ../../node_modules/.pnpm/whatwg-url@11.0.0/node_modules/whatwg-url/lib/URL.js (/home/mateus/WebstormProjects/leetcode-problem-storer/my-turborepo/apps/api/dist/index.js:47889:17)
api:dev:     at __require (/home/mateus/WebstormProjects/leetcode-problem-storer/my-turborepo/apps/api/dist/index.js:46:50)
api:dev:     at ../../node_modules/.pnpm/whatwg-url@11.0.0/node_modules/whatwg-url/webidl2js-wrapper.js (/home/mateus/WebstormProjects/leetcode-problem-storer/my-turborepo/apps/api/dist/index.js:48235:16)
api:dev:     at __require (/home/mateus/WebstormProjects/leetcode-problem-storer/my-turborepo/apps/api/dist/index.js:46:50)
api:dev:     at ../../node_modules/.pnpm/whatwg-url@11.0.0/node_modules/whatwg-url/index.js (/home/mateus/WebstormProjects/leetcode-problem-storer/my-turborepo/apps/api/dist/index.js:48246:60)
api:dev:     at __require (/home/mateus/WebstormProjects/leetcode-problem-storer/my-turborepo/apps/api/dist/index.js:46:50)
api:dev:     at ../../node_modules/.pnpm/mongodb-connection-string-url@2.6.0/node_modules/mongodb-connection-string-url/lib/index.js (/home/mateus/WebstormProjects/leetcode-problem-storer/my-turborepo/apps/api/dist/index.js:48375:24)
api:dev: 
api:dev: Node.js v18.17.0
`

Package manager:

npm

Starting command

pnpm dev

The actual frontend server starts just fine, the issue is with my expressjs server. How can I fix this?

**Comment by Rakoski** [comment]
Problem corrected ✔️

This was linked to a dependency issue. When I cd into my api folder and installed mongodb, mongoose and express, via package.json and npm instead of the pnpm the documentation recommended, it worked
